BIZ-1 Main infrastructure - Server
multicora/PVM pull request #1
Opened 2016-11-04 08:18 UTC by FeditskiyRoman

2016-11-07 13:03 UTC, dmitrij-borchuk requested changes

2016-11-07 13:03 UTC, dmitrij-borchuk commented on app/server.js
> +  function registerACL(server) {
Where do you call it?

2016-11-07 13:03 UTC, dmitrij-borchuk commented on app/server.js
> +          console.log(err);
Remove console.log

2016-11-07 13:03 UTC, dmitrij-borchuk commented on app/server.js
> +        if (err) {
Use short form:
err ? reject() : resolve();

2016-11-07 13:03 UTC, dmitrij-borchuk commented on app/dataConnection.js
> +var mysql = require('mysql');
Where do you use this file?

2016-11-07 13:03 UTC, dmitrij-borchuk commented on app/server.js
> +       const AuthHeader = require('hapi-auth-header');
Fix identation

2016-11-07 13:03 UTC, dmitrij-borchuk commented on app/server.js
> +           server.auth.strategy('simple', 'auth-header', {
Fix identation

2016-11-07 13:03 UTC, dmitrij-borchuk commented on app/server.js
> +            validateFunc: function (tokens, callback) {
Move this function to end if file

2016-11-07 13:03 UTC, dmitrij-borchuk commented on app/server.js
> +              var request = this;
Where do you use this variable?

2016-11-07 13:03 UTC, dmitrij-borchuk commented on app/server.js
> +               DAL.users.getUserByToken(tokens[headerName], function (err, user) {
Dal is not exist

2016-11-07 13:19 UTC, FeditskiyRoman commented on app/server.js
> +              var request = this;
fixed

2016-11-07 13:19 UTC, FeditskiyRoman commented on app/server.js
> +  function registerACL(server) {
fixed

2016-11-07 13:19 UTC, FeditskiyRoman commented on app/server.js
> +        if (err) {
fixed

2016-11-07 13:19 UTC, FeditskiyRoman commented on app/server.js
> +          console.log(err);
fixed

2016-11-07 13:19 UTC, FeditskiyRoman commented on app/server.js
> +               DAL.users.getUserByToken(tokens[headerName], function (err, user) {
fixed

2016-11-07 13:20 UTC, FeditskiyRoman commented on app/dataConnection.js
> +var mysql = require('mysql');
var connection = mysql.createConnection({

2016-11-08 10:05 UTC, dmitrij-borchuk requested changes

2016-11-08 10:05 UTC, dmitrij-borchuk commented on backend/server.js
> +  function connectToDB() {
Where do you call it?

2016-11-08 10:05 UTC, dmitrij-borchuk commented on backend/dataConnection.js
> +  connection.query('SELECT * FROM pvmDB', function(err, rows, fields) {
What for?

2016-11-08 10:05 UTC, dmitrij-borchuk commented on backend/server.js
> +        if (err) {
Use "err ? reject() : resolve();"

2016-11-08 10:06 UTC, dmitrij-borchuk commented
Folder "dist" should be ignored

2016-11-08 10:53 UTC, dmitrij-borchuk requested changes

2016-11-08 10:53 UTC, dmitrij-borchuk commented on backend/dataConnection.js
> +  host: 'localhost',
Move this settings to config

2016-11-08 10:53 UTC, dmitrij-borchuk commented on backend/dataConnection.js
> +module.exports = function() {
It should return promise

2016-11-08 10:53 UTC, dmitrij-borchuk commented on backend/dataConnection.js
>          console.log("Database is connected ... ");
Remove console.log
It should call "promice.reject()"

2016-11-08 11:34 UTC, dmitrij-borchuk commented
Remove forler "dist" from pull request

2016-11-08 11:35 UTC, dmitrij-borchuk requested changes

2016-11-08 11:35 UTC, dmitrij-borchuk commented on backend/server.js
> +      connectDB()
Should return result

2016-11-08 12:01 UTC, dmitrij-borchuk requested changes

2016-11-08 12:01 UTC, dmitrij-borchuk commented on backend/dataConnection.js
> +        err ? reject() : resolve();
"reject" should be calld with "arr" as a param

2016-11-08 12:01 UTC, dmitrij-borchuk requested changes

2016-11-08 12:01 UTC, dmitrij-borchuk commented on backend/dataConnection.js
> +        err ? reject() : resolve();
"reject" should be calld with "arr" as a param

2016-11-10 09:21 UTC, dmitrij-borchuk approved these changes

2016-11-10 09:22 UTC, merged