Biz 434
multicora/PVM pull request #119
Opened 2017-08-08 14:12 UTC by FeditskiyRoman

2017-08-13 13:10 UTC, dmitrij-borchuk requested changes

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/component.js
> +      item.expandClass = 'expanded';
Please, move class name to the template

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/component.js
> +      item.expandClass = '';
Please, move class name to the template

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +  .main-content {
Please fix the code style

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +      font-family: 'Roboto Bold';
Class name in not correct

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +.result {
Please move it from the global context

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +#full-log {
Please move it from the global context and use class instead of id

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +.timeline-title {
Please move it from the global context

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +.pr-bar-container.expanded {
Please move it from the global context

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +  display: block;
Please fix code style

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +.expand-btn-container {
Please move it from the global context

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +}
Don't forget to add empty string to the end of filas

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +      display: block;
Use class with "display: none" to hide if you need and remove this class to show

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/tpl.pug
> +            span(ng-if="!vm.toUser && item.email && item.email != 'null' && item.email != 'undefined'") to: {{item.email}}
Remove string 'null' and 'undefined'

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/tpl.pug
> +            span(ng-if="!vm.toUser && !item.email || item.email === 'null' || item.email === 'undefined'") Public
Remove string 'null' and 'undefined'

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/tpl.pug
> +            .bubble(ng-if="vm.toUser && !item.CONVERSATION_IS_VIEWED")
Data should not have a constants like CONVERSATION_IS_VIEWED

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/tpl.pug
> +            .bubble(ng-if="vm.toUser && !item.CONVERSATION_IS_VIEWED")
What is CONVERSATION_IS_VIEWED?

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/conversationsList/tpl.pug
> +                    .times(ng-if="item.CONVERSATION_IS_VIEWED.counter > 1 && item.CONVERSATION_IS_VIEWED.counter < 9") {{ item.CONVERSATION_IS_VIEWED.counter }}
Why constant has some not constant property?

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/components/notifications/component.js
> +
use "return notificationsService.messageGenerator(notification);"

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/conversations/ctrl.js
> +    vm.getObjectKeyName = function (numb, object) {
https://docs.angularjs.org/api/ng/directive/ngRepeat
Remove this function, use angular for it

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/conversations/ctrl.js
> +              conversation[event.type].counter++;
This logic looks very difficult and hard to scale

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/conversations/style.scss
> +
Remove this empty line

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/conversations/style.scss
> +    .title {
Add an empty line

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/conversations/style.scss
> +    @media (min-width: 330px) {
Add an empty line

2017-08-13 13:10 UTC, dmitrij-borchuk commented on dev/conversations/style.scss
> +
Remove this empty line and please fix code style

2017-08-15 18:24 UTC, dmitrij-borchuk requested changes

2017-08-15 18:24 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +    .bold-font {
Move font-family out of the component
Use "font-weight" property

2017-08-15 18:24 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +        display: none;
Use class to hide and remove class to show

2017-08-15 18:24 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
>            display: none;
Use class to hide and remove class to show

2017-08-15 18:24 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +          display: none;
Use class to hide and remove class to show

2017-08-15 18:24 UTC, dmitrij-borchuk commented on dev/components/conversationsList/style.scss
> +    display: none;
Use class to hide and remove class to show

2017-08-15 18:24 UTC, dmitrij-borchuk commented on dev/components/conversationsList/tpl.pug
> +            span(ng-if="!vm.toUser && item.email && item.email != null && item.email != undefined") to: {{item.email}}
If "item.email" will be null or undefined if will not pass this part "!vm.toUser && item.email" so looks like " && item.email != null && item.email != undefined" will never run

2017-08-15 18:24 UTC, dmitrij-borchuk commented on dev/components/conversationsList/tpl.pug
> +            span(ng-if="!vm.toUser && !item.email || item.email === null || item.email === undefined") Public
looks like " || item.email === null || item.email === undefined" will never run

2017-08-15 18:25 UTC, dmitrij-borchuk requested changes

2017-08-15 18:25 UTC, dmitrij-borchuk commented on dev/components/conversationsList/component.js
> +        conversation.expandClass = '';
Please, move class name to the template

2017-08-16 11:56 UTC, dborchuk approved these changes

2017-08-16 11:56 UTC, merged