Biz 104 reset password
multicora/PVM pull request #15
Opened 2016-12-31 11:46 UTC by FeditskiyRoman

2017-01-02 16:38 UTC, dmitrij-borchuk reviewed
Error: SyntaxError: Unexpected token M in JSON at position 0

After I have clicked send button

2017-01-02 16:38 UTC, dmitrij-borchuk commented on app/components/reset-password-page.js
> +  store: Ember.inject.service(),
What for?

2017-01-02 16:38 UTC, dmitrij-borchuk commented on app/components/new-password-page.js
> +  store: Ember.inject.service(),
What for?

2017-01-02 16:38 UTC, dmitrij-borchuk commented on backend/routing/users.js
> +      handler: function (request, reply) {
Move to controller

2017-01-02 16:38 UTC, dmitrij-borchuk commented on backend/routing/users.js
> +            to: '<bizkonect.project@gmail.com>', //for test
How user can receive email?

2017-01-02 16:54 UTC, dmitrij-borchuk requested changes

2017-01-02 16:54 UTC, dmitrij-borchuk commented on app/templates/components/login-page.hbs
> +        {{#link-to "reset-password"}}reset password{{/link-to}}
Should be shown permanently

2017-01-02 16:54 UTC, dmitrij-borchuk commented on backend/dal/users.js
> +    newPassword: (resetToken, password) => {
Reset token should be cleared

2017-01-02 16:54 UTC, dmitrij-borchuk commented on backend/dal/users.js
> +        'NOT NULL;'
Why "not null"?

2017-01-02 16:54 UTC, dmitrij-borchuk commented on backend/routing/users.js
> +          reply(err);
Add Boom

2017-01-02 16:54 UTC, dmitrij-borchuk commented on backend/routing/users.js
> +              reply(err);
Add Boom

2017-01-02 17:17 UTC, FeditskiyRoman commented on backend/routing/users.js
> +            to: '<bizkonect.project@gmail.com>', //for test
it's for testing becouse we have only user with user@user.com password and it isn't valid

2017-01-03 07:45 UTC, FeditskiyRoman commented on backend/routing/users.js
> +      handler: function (request, reply) {
fixed

2017-01-03 10:38 UTC, FeditskiyRoman commented on backend/dal/users.js
> +    newPassword: (resetToken, password) => {
fixed

2017-01-03 15:17 UTC, dmitrij-borchuk requested changes

2017-01-03 15:17 UTC, dmitrij-borchuk commented on backend/dal/users.js
> +        let request2 = [
It can be done in one request

2017-01-03 15:17 UTC, dmitrij-borchuk commented on backend/controllers/users.js
> +      return result;
'result' will be returned before will be assigned

2017-01-03 15:17 UTC, dmitrij-borchuk commented on backend/controllers/users.js
> +      return result;
You should use promice

2017-01-03 15:18 UTC, dmitrij-borchuk requested changes

2017-01-03 15:18 UTC, dmitrij-borchuk commented on backend/routing/users.js
> +      handler: function (request, reply) {
Move to controller all logic from handler

2017-01-03 18:54 UTC, dmitrij-borchuk requested changes

2017-01-03 18:54 UTC, dmitrij-borchuk commented on app/templates/components/login-page.hbs
> +        {{#link-to "reset-password"}}Reset{{/link-to}}
Change to "Forgot password"

2017-01-03 18:58 UTC, dmitrij-borchuk approved these changes

2017-01-03 19:00 UTC, merged