Biz 155 templates
multicora/PVM pull request #29
Opened 2017-03-03 15:30 UTC by FeditskiyRoman

2017-03-10 08:18 UTC, dmitrij-borchuk requested changes

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/components/templatesList/component.js
> +      use: '&',
what is use?

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/components/templatesList/component.js
> +      delete: '&',
rename to 'onDelete'

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/components/templatesList/style.scss
> +.content {
Class name is too common

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/components/videoList/tpl.pug
> +        show-send-handler="vm.showSendHandler"
I am not sure that it is working

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/components/videoTile/tpl.pug
> +      ng-if="vm.showSendHandler"
Is the the 'showSendHandler' function? If yes why you are checking if it exists? If not why it has 'handler' in the name?

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/config.js
> +    }).when('/template/:id/:templateId', {
What is 'id'?

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/conversations/tpl.pug
> +        p.user-role {{vm.user.message}}
Class name is .user-role but content is message. Something wrong

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/library/ctrl.js
> +    vm.showSendHandler = true;
'Handler' should be in names of the callbacks

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/library/ctrl.js
> +      $location.path('template/' + video.id + '/null');
What for 'null'?

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/library/ctrl.js
> +      $location.path('template/null/' + id);
What for 'null'?

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/library/ctrl.js
> +        console.log(vm.templatesList);
Remove

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/library/ctrl.js
> +        vm.videosList = res.data.data;
data.data ???

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/library/tpl.pug
> +    use="vm.useTemplate($data)"
What is 'use'?

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/template/ctrl.js
> +    if ($routeParams.templateId === 'null') {
String 'null'???

2017-03-10 08:18 UTC, dmitrij-borchuk commented on dev/template/ctrl.js
> +    function checkName() {
Should return the result

2017-03-10 08:18 UTC, dmitrij-borchuk commented
Please merge dev to this branch

2017-03-10 09:00 UTC, FeditskiyRoman commented on dev/library/ctrl.js
> +        vm.videosList = res.data.data;
response from server is data: {data: {video}}

2017-03-10 09:02 UTC, FeditskiyRoman commented on dev/config.js
> +    }).when('/template/:id/:templateId', {
I need one url for two differents page, if :id===null i show one page, if templateId===null i show another

2017-03-10 13:52 UTC, FeditskiyRoman commented on dev/library/ctrl.js
> +        vm.videosList = res.data.data;
fixed

2017-03-11 07:49 UTC, dmitrij-borchuk requested changes

2017-03-11 07:49 UTC, dmitrij-borchuk commented on dev/library/ctrl.js
> +        vm.videosList = res.data.data;
it is still here

2017-03-11 07:58 UTC, dmitrij-borchuk requested changes

2017-03-11 07:58 UTC, dmitrij-borchuk commented on dev/library/ctrl.js
> +      $location.path('template/' + video.id + '/null');
What for 'null'?

2017-03-13 06:21 UTC, dmitrij-borchuk approved these changes

2017-03-13 06:22 UTC, merged