Reworking emails templates
multicora/PVM pull request #43
Opened 2017-03-24 15:21 UTC by FeditskiyRoman

2017-03-25 01:05 UTC, dmitrij-borchuk requested changes

2017-03-25 01:05 UTC, dmitrij-borchuk commented on backend/controllers/notifications.js
> +        if (!user.firstName) {
user this style:
user.firstName = user.firstName || '';

2017-03-25 01:05 UTC, dmitrij-borchuk commented on backend/controllers/users.js
> +                // TODO: need to use 'resolve();' or 'resolve(res);'
Please pay attention to TODO

2017-03-27 07:37 UTC, FeditskiyRoman commented on backend/controllers/users.js
> +                // TODO: need to use 'resolve();' or 'resolve(res);'
fixed

2017-03-27 18:45 UTC, dmitrij-borchuk approved these changes

2017-03-27 20:04 UTC, merged