Biz 32 video management list
multicora/PVM pull request #7
Opened 2016-12-09 17:34 UTC by FeditskiyRoman

2016-12-09 18:02 UTC, dmitrij-borchuk reviewed
Remove "public/assets/menu-icon.png"

2016-12-09 18:02 UTC, dmitrij-borchuk commented on app/templates/components/library-add-button-record.hbs
> +<div class="record">
<div class="record">
  {{yield}}
  <p>Record</p>
</div>

2016-12-09 18:02 UTC, dmitrij-borchuk commented on app/components/library-container.js
> +  isShownRecord: false,
Rename to "isShownRecordPopup"

2016-12-09 18:02 UTC, dmitrij-borchuk commented on app/styles/variables.scss
> +$red-buttons-color:    #E53935;
Change to "record {bla bla}"

2016-12-09 18:02 UTC, dmitrij-borchuk commented on app/templates/components/library-navigation.hbs
> +      <li>
Move to array in component controller

2016-12-09 18:02 UTC, dmitrij-borchuk commented on backend/dal/video.js
> +          (err || !response.length) ? reject(err) : resolve(response);
Remove "!response.length"

2016-12-09 18:22 UTC, dmitrij-borchuk requested changes

2016-12-09 18:22 UTC, dmitrij-borchuk commented on app/styles/library.scss
> +  min-height: 100%;
Remove

2016-12-09 18:22 UTC, dmitrij-borchuk commented on app/styles/library.scss
> +        display: block;
Remove

2016-12-09 18:22 UTC, dmitrij-borchuk commented on app/styles/library.scss
> +        display: block;
Check

2016-12-09 18:22 UTC, dmitrij-borchuk commented on app/styles/library.scss
> +        overflow: hidden;
Move to separate class

2016-12-09 18:22 UTC, dmitrij-borchuk commented on app/styles/library.scss
> +    .ember-view {
Remove or rename

2016-12-12 08:44 UTC, FeditskiyRoman commented on app/components/library-container.js
> +  isShownRecord: false,
fixed

2016-12-12 08:51 UTC, FeditskiyRoman commented on app/styles/variables.scss
> +$red-buttons-color:    #E53935;
fixed

2016-12-12 08:52 UTC, FeditskiyRoman commented on backend/dal/video.js
> +          (err || !response.length) ? reject(err) : resolve(response);
fixed

2016-12-12 08:54 UTC, FeditskiyRoman commented on app/styles/library.scss
> +        display: block;
fixed

2016-12-12 08:54 UTC, FeditskiyRoman commented on app/styles/library.scss
> +  min-height: 100%;
fixed

2016-12-12 08:55 UTC, FeditskiyRoman commented on app/styles/library.scss
> +        display: block;
fixed

2016-12-12 08:57 UTC, FeditskiyRoman commented on app/styles/library.scss
> +        overflow: hidden;
fixed

2016-12-12 09:06 UTC, FeditskiyRoman commented on app/styles/library.scss
> +    .ember-view {
fixed

2016-12-12 10:48 UTC, FeditskiyRoman commented on app/templates/components/library-add-button-record.hbs
> +<div class="record">
fixed

2016-12-12 11:07 UTC, dmitrij-borchuk approved these changes

2016-12-12 11:09 UTC, merged